# Generated by Django 3.0.4 on 2020-04-14 09:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=200, unique=True)),
                ('name_db', models.CharField(max_length=200, null=True)),
                ('dbms', models.CharField(choices=[('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('Neo4j', 'Neo4j')], max_length=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('graph', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
